function homePage() {
  return `${header()}<main>
    <section class="hero page-shell">
      <div class="hero__copy">
        <p class="eyebrow">Ontario's student volunteer network</p><h1>Valantir</h1>
        <p class="hero__subtitle">A platform connecting students to volunteer opportunities.</p>
        <div class="hero__actions"><a class="button button--dark" href="/signup/student">Find opportunities ${arrow}</a><a class="button button--light" href="/signup/business">Post an opportunity</a></div>
        <form class="newsletter"><label for="newsletter-email">Join the newsletter.</label><div class="newsletter__row"><input id="newsletter-email" type="email" required placeholder="you@example.com"><button type="submit" aria-label="Join newsletter">${arrow}</button></div><p class="form-note" role="status">Thanks — you are on the list.</p></form>
      </div>
      <div class="hero__side">
        <div class="orbit" aria-hidden="true"><span class="orbit__dot orbit__dot--one"></span><span class="orbit__dot orbit__dot--two"></span><span class="orbit__dot orbit__dot--three"></span><div class="orbit__center"><img src="/logo.webp" alt=""></div></div>
        <div class="testimonial-stack">${testimonials.map((item, index) => `<article class="testimonial-card" style="--card-right:${index * 22}px;--card-bottom:${index * 20}px;--card-rotate:${(index - 1) * 2}deg"><p>“${item[0]}”</p><div><strong>${item[1]}</strong><span>${item[2]}</span></div></article>`).join('')}</div>
      </div>
      <a class="scroll-cue" href="#product">scroll down <span>↓</span></a>
    </section>
    <section class="product-section" id="product"><div class="page-shell product-section__inner"><div class="section-heading section-heading--inverse"><p class="eyebrow">One place. Every volunteer hour.</p><h2>Browse, apply, message, and track it all.</h2></div><div class="laptop-wrap"><img src="/laptop.png" onerror="this.onerror=null;this.src='/laptop.webp'" alt="Valantir opportunity browser with listings and a map" decoding="async"><div class="floating-label floating-label--left">Matched to your interests</div><div class="floating-label floating-label--right">Hours, verified</div></div></div></section>
    <section class="section page-shell about" id="about"><div class="section-kicker"><span>01</span> About</div><div class="about__content"><div><h2>What is<br>Valantir?</h2><p>Valantir is where students find volunteer work nearby and log hours that count. Browse openings from local nonprofits and businesses, apply in seconds, and get every hour confirmed by the organization you worked with.</p><p class="muted-large">No spreadsheets. No chasing signatures.</p><a class="inline-arrow" href="/signup/student">Start volunteering ${arrow}</a></div><div class="venn-card"><img src="/venn.png" onerror="this.onerror=null;this.src='/venn.webp'" alt="Valantir connects students, organizations, and meaningful local impact" loading="lazy" decoding="async"></div></div></section>
    <section class="mission" id="mission"><div class="page-shell"><div class="section-kicker section-kicker--light"><span>02</span> Mission</div><div class="mission__title"><h2>Make your<br><em>40 hours</em><br>count.</h2><p>Volunteer hours shouldn't be a scavenger hunt. Valantir matches students with local organizations that need them, turning every hour into experience, references, and resume-worthy skills.</p></div><div class="mission-grid">
      <article class="mission-card mission-card--orange"><div class="mission-card__number">01</div><img src="/mission-orange.png" onerror="this.onerror=null;this.src='/mission-orange.webp'" alt="Community volunteers working together outdoors" loading="lazy" decoding="async"><h3>Find your place</h3><p>Discover work that matches what you care about, where you live, and when you are free.</p></article>
      <article class="mission-card mission-card--green"><div class="mission-card__number">02</div><img src="/mission-green.png" onerror="this.onerror=null;this.src='/mission-green.webp'" alt="A group of young volunteers and community organizers" loading="lazy" decoding="async"><h3>Build something real</h3><p>Turn required hours into skills, references, friendships, and a stronger community.</p></article>
    </div><blockquote class="impact-quote"><p>“More than 75% of entering college students want to help others, yet only 26% actually volunteer. We're at an all-time high of desire to do good, but far from an all-time high of actually doing it.”</p><cite>Do Good Institute, University of Maryland</cite></blockquote></div></section>
    <section class="section page-shell founders" id="founders"><div class="section-kicker"><span>03</span> Founders</div><div class="founders__intro"><h2>Built by students,<br>for students.</h2><p>We're two Oakville high school students. We watched classmates scrape together hours from anyone who'd sign a sheet, while local nonprofits sat short-staffed. So we built the bridge.</p></div><div class="founder-grid">
      <article class="founder-card"><div class="founder-card__image"><img src="/team-hani.png" onerror="this.onerror=null;this.src='/team-hani.webp'" alt="Hani Zaidi" loading="lazy" decoding="async"></div><div class="founder-card__meta"><span>Co-founder</span><h3>Hani Zaidi</h3><p>Programming + Marketing</p></div></article>
      <article class="founder-card founder-card--offset"><div class="founder-card__image"><img src="/team-nathan.png" onerror="this.onerror=null;this.src='/team-nathan.webp'" alt="Nathan Jia" loading="lazy" decoding="async"></div><div class="founder-card__meta"><span>Co-founder</span><h3>Nathan Jia</h3><p>Strategy + Marketing</p></div></article>
    </div></section>
    <section class="organizations" id="organizations"><div class="page-shell"><div class="section-kicker"><span>04</span> For organizations</div><div class="organizations__intro"><h2>Find the right help,<br>right when you need it.</h2><p>Post an opportunity in minutes. Get matched with students whose interests, location, and availability fit. Confirm their hours when the work is done. Whether you're a nonprofit, a small business, or a community group, Valantir handles the matching so you can focus on the work.</p></div><div class="steps">
      ${[['1','Post an opportunity','Describe what you need help with. It takes minutes, and posting is always free.'],['2','Review applicants','Students nearby apply to you. Accept the ones that fit, or let spots fill instantly.'],['3','Confirm hours','When the work is done, confirm volunteer hours in one click. No paperwork.']].map(step => `<article class="step"><span class="step__number">${step[0]}</span><div><h3>${step[1]}</h3><p>${step[2]}</p></div></article>`).join('')}
      </div><div class="organization-cta"><div class="benefits"><span>Free for organizations</span><span>Students in your area</span><span>No paperwork or admin overhead</span></div><a class="button button--dark" href="/signup/business">Create a free organization account ${arrow}</a></div></div></section>
    <section class="section page-shell faq"><div class="section-kicker"><span>05</span> Common Q&amp;A</div><div class="faq__layout"><h2>Questions,<br>answered.</h2><div class="faq-list">${faqs.map((item, index) => `<article class="faq-item ${index === 0 ? 'is-open' : ''}"><button aria-expanded="${index === 0}"><span>${item[0]}</span><span>${index === 0 ? '−' : '+'}</span></button><div class="faq-item__answer"><p>${item[1]}</p></div></article>`).join('')}</div></div></section>
  </main>${footer()}`
}
