import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { issueTicketToken } from '@/lib/tickets/signing'
import { isSupabaseConfigured } from '@/lib/supabase/env'
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
export const runtime='nodejs'
async function resign(admin,ticketId){const{data:t,error}=await admin.from('tickets').select('id,event_id,order_id,owner_id,ticket_number,token_version').eq('id',ticketId).single();if(error)throw error;const signed=issueTicketToken(t);const{error:u}=await admin.from('tickets').update({signed_token:signed.token,signed_code_hash:signed.hash,signed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',ticketId);if(u)throw u}
export async function POST(request){if(!isSupabaseConfigured())return NextResponse.json({error:'Ticket transfers are unavailable.'},{status:503});const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:'Sign in.'},{status:401});const b=await request.json().catch(()=>({}));try{let r;if(b.action==='request'){if(!UUID.test(String(b.ticketId||'')))throw new Error('Ticket not found.');r=await s.rpc('request_ticket_transfer_v1',{target_ticket:b.ticketId,recipient_username:String(b.recipient||'').replace(/^@/,'').trim()})}else if(b.action==='accept'){if(!UUID.test(String(b.transferId||'')))throw new Error('Transfer not found.');r=await s.rpc('accept_ticket_transfer_v1',{target_transfer:b.transferId});if(!r.error&&r.data?.ticket_id)await resign(createAdminClient(),r.data.ticket_id)}else if(b.action==='cancel'){if(!UUID.test(String(b.transferId||'')))throw new Error('Transfer not found.');r=await s.rpc('cancel_ticket_transfer_v1',{target_transfer:b.transferId})}else throw new Error('Unknown transfer action.');if(r.error)throw r.error;return NextResponse.json({ok:true,result:r.data})}catch(e){return NextResponse.json({error:String(e?.message||'Transfer failed.').slice(0,200)},{status:400})}}
