import Link from 'next/link'
import { AuthMessage } from '@/components/auth-message'
import { EmptyState } from '@/components/empty-state'
import { renderProductPage } from '@/lib/app/render-product-page'
import { getFriendsSnapshot } from '@/lib/app/social-data'
import { blockProfile, followHost, openDirectConversation, removeFriend, respondFriendRequest, saveSocialPrivacy, sendFriendRequest, setCloseFriend, unblockProfile } from '@/app/social/actions'

export const dynamic = 'force-dynamic'
export const metadata = { title: 'Friends' }

function PersonCard({ person, current = 'result' }) {
  const next = '/friends'
  return <article className="social-person-card"><div className="social-avatar">{String(person.display_name || person.username || 'P').slice(0,1).toUpperCase()}</div><div className="social-person-copy"><strong>{person.display_name || 'Puddle user'}</strong><span>@{person.username || 'puddle_user'}{person.city ? ` · ${person.city}` : ''}</span>{person.bio ? <p>{person.bio}</p> : null}{Number.isFinite(Number(person.mutual_count)) ? <small>{person.mutual_count} mutual friend{Number(person.mutual_count)===1?'':'s'}</small> : null}</div><div className="social-person-actions">
    {current === 'incoming' ? <><form action={respondFriendRequest}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="response" value="accept"/><input type="hidden" name="next" value={next}/><button type="submit">Accept</button></form><form action={respondFriendRequest}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="response" value="decline"/><input type="hidden" name="next" value={next}/><button className="quiet-button" type="submit">Decline</button></form></> : null}
    {current === 'friend' ? <><form action={openDirectConversation}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="next" value={next}/><button type="submit">Message</button></form><form action={setCloseFriend}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="enabled" value={person.closeFriend ? 'false':'true'}/><input type="hidden" name="next" value={next}/><button className="quiet-button" type="submit">{person.closeFriend ? 'Remove close':'Close friend'}</button></form><form action={removeFriend}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="next" value={next}/><button className="quiet-button" type="submit">Remove</button></form></> : null}
    {current === 'result' && !person.is_friend && person.request_state !== 'pending' ? <form action={sendFriendRequest}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="next" value={next}/><button type="submit">Add friend</button></form> : null}
    {current === 'result' && person.is_friend ? <form action={openDirectConversation}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="next" value={next}/><button type="submit">Message</button></form> : null}
    {current === 'result' && person.request_state === 'pending' && !person.is_friend ? <span className="request-state">Request pending</span> : null}
    {current !== 'blocked' ? <form action={blockProfile}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="next" value={next}/><button className="danger-link" type="submit">Block</button></form> : <form action={unblockProfile}><input type="hidden" name="profile_id" value={person.id}/><input type="hidden" name="next" value={next}/><button type="submit">Unblock</button></form>}
  </div></article>
}

export default async function FriendsPage({ searchParams }) {
  const params = await searchParams
  const search = String(params?.q || '').trim().slice(0,80)
  return renderProductPage(async (session) => {
    const data = await getFriendsSnapshot(session, search)
    return <><section className="page-heading-row"><div><span className="section-pill section-pill-mint">Make plans together</span><h1 className="product-title">Your people.</h1><p>Find friends, share events and places, and coordinate real plans. Puddle never swipes through people.</p></div><Link className="splash-button splash-button-mint" href="/inbox">Open inbox</Link></section><AuthMessage searchParams={params}/>
      <section className="friend-stats"><article><strong>{data.friends.length}</strong><span>friends</span></article><article><strong>{data.incoming.length}</strong><span>requests</span></article><article><strong>{data.friends.filter((friend)=>friend.closeFriend).length}</strong><span>close friends</span></article><article><strong>{data.follows.length}</strong><span>hosts followed</span></article></section>
      <section className="social-privacy-panel"><div><span className="section-pill section-pill-yellow">Privacy</span><h2>Control your social visibility.</h2><p>These settings affect friend discovery, activity sharing, and event-participant messaging.</p></div><form action={saveSocialPrivacy}><label>Activity visibility<select name="activity_visibility" defaultValue={session.profile.activity_visibility || 'friends'}><option value="private">Only me</option><option value="close_friends">Close friends</option><option value="friends">Friends</option><option value="public">Public</option></select></label><label className="settings-toggle"><input type="checkbox" name="allow_friend_requests" defaultChecked={session.profile.allow_friend_requests ?? true}/><span>Allow username friend requests</span></label><label className="settings-toggle"><input type="checkbox" name="allow_event_messages" defaultChecked={session.profile.allow_event_messages ?? true}/><span>Allow operational messages from event hosts and opted-in attendees</span></label><button type="submit">Save privacy</button></form></section>
      <section className="friend-search-panel"><div><h2>Find by username.</h2><p>Search only returns people who allow friend requests and are not blocked.</p></div><form><input name="q" defaultValue={search} minLength="2" maxLength="80" placeholder="@username or display name"/><button type="submit">Search</button></form></section>
      {search ? <section className="social-section"><div className="social-section-heading"><h2>Search results</h2><span>{data.results.length}</span></div>{data.results.length ? <div className="social-person-list">{data.results.map((person)=><PersonCard person={person} key={person.id}/>)}</div> : <EmptyState icon="⌕" title="No one found." description="Try another username or display name." actionHref="/friends" actionLabel="Clear search"/>}</section> : null}
      {data.incoming.length ? <section className="social-section"><div className="social-section-heading"><h2>Friend requests</h2><span>{data.incoming.length}</span></div><div className="social-person-list">{data.incoming.map((person)=><PersonCard person={person} current="incoming" key={person.id}/>)}</div></section> : null}
      <section className="social-section"><div className="social-section-heading"><h2>Friends</h2><span>{data.friends.length}</span></div>{data.friends.length ? <div className="social-person-list">{data.friends.map((person)=><PersonCard person={person} current="friend" key={person.id}/>)}</div> : <EmptyState icon="☺" title="Bring your people in." description="Search by username and send a friend request to start sharing plans." actionHref="/friends?q=puddle" actionLabel="Try a search"/>}</section>
      {data.follows.length ? <section className="social-section"><div className="social-section-heading"><h2>Followed hosts</h2><span>{data.follows.length}</span></div><div className="social-person-list">{data.follows.map((follow)=><article className="social-person-card" key={follow.host_profile_id}><div className="social-avatar">✦</div><div className="social-person-copy"><strong>{follow.host_profiles?.name || 'Puddle host'}</strong><span>{String(follow.host_profiles?.kind || 'host').replaceAll('_',' ')}</span></div><div className="social-person-actions"><Link href={`/hosts/${follow.host_profiles?.slug}`}>View host</Link><form action={followHost}><input type="hidden" name="host_id" value={follow.host_profile_id}/><input type="hidden" name="enabled" value="false"/><input type="hidden" name="next" value="/friends"/><button className="quiet-button" type="submit">Unfollow</button></form></div></article>)}</div></section> : null}
      {data.blocked.length ? <details className="blocked-people"><summary>Blocked profiles ({data.blocked.length})</summary><div className="social-person-list">{data.blocked.map((person)=><PersonCard person={person} current="blocked" key={person.id}/>)}</div></details> : null}
    </>
  })
}
