import { test, expect } from '@playwright/test'

test('landing phone demo routes are public, same-origin frameable, and keep other pages protected from framing', async ({ request }) => {
  const demo = await request.get('/landing-demo/swipe')
  expect(demo.ok()).toBeTruthy()
  expect(demo.headers()['x-frame-options'] || '').toContain('SAMEORIGIN')
  expect(demo.headers()['content-security-policy'] || '').toContain("frame-ancestors 'self'")

  const signup = await request.get('/signup')
  expect(signup.headers()['x-frame-options'] || '').toContain('DENY')
  expect(signup.headers()['content-security-policy'] || '').toContain("frame-ancestors 'none'")
})

test('public Swipe phone keeps the Figma screen identity and real draggable mechanics', async ({ page }) => {
  await page.goto('/landing-demo/swipe')
  const screen = page.locator('[data-demo-screen="swipe"]')
  await expect(screen).toBeVisible()
  await expect(screen).toHaveAttribute('data-figma-screen', '40:641')
  await expect(screen.getByRole('img', { name: 'Puddle' })).toBeVisible()

  const card = screen.locator('.landing-demo-swipe-card')
  await expect(card).toHaveAttribute('data-place-id', 'maple-grove')
  await screen.getByRole('button', { name: 'Open Maple Grove Park' }).click()
  await expect(page.getByRole('dialog', { name: 'Maple Grove Park details' })).toBeVisible()
  await page.getByRole('button', { name: 'Close details' }).click()
  const box = await card.boundingBox()
  expect(box).toBeTruthy()
  await page.mouse.move(box.x + box.width * .5, box.y + box.height * .45)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width * .86, box.y + box.height * .45, { steps: 8 })
  await page.mouse.up()
  await expect(card).toHaveAttribute('data-place-id', 'firehall')
  await expect(screen.getByRole('button', { name: 'Back' })).toBeEnabled()
  await screen.getByRole('button', { name: 'Back' }).click()
  await expect(card).toHaveAttribute('data-place-id', 'maple-grove')
})

test('Saved, Feed, and Profile phone demos expose their corresponding Figma interactions', async ({ page }) => {
  await page.goto('/landing-demo/save')
  const saved = page.locator('[data-demo-screen="save"]')
  await expect(saved).toBeVisible()
  await expect(saved).toHaveAttribute('data-figma-screen', '25:180')
  await saved.getByRole('button', { name: 'Plans', exact: true }).click()
  await expect(saved.getByText('Saturday · 7:00 PM')).toBeVisible()
  await expect(saved.getByText('Night Gallery', { exact: true })).toBeVisible()
  await saved.locator('.landing-demo-mobile-header .landing-demo-segment').getByRole('button', { name: 'Saved', exact: true }).click()
  await saved.getByPlaceholder('Search a saved puddle...').fill('film')
  await expect(saved.getByText('Film House', { exact: true })).toBeVisible()
  await expect(saved.getByText('Firehall Cool Bar Hot Grill', { exact: true })).toHaveCount(0)
  await saved.getByText('Film House', { exact: true }).click()
  const savedDialog = page.getByRole('dialog', { name: 'Film House details' })
  await expect(savedDialog).toBeVisible()
  await expect(savedDialog.getByRole('button', { name: 'Close details' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(savedDialog.getByRole('button', { name: 'Close details' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(savedDialog).toBeHidden()
  await expect(saved.getByRole('button', { name: /Film House/ })).toBeFocused()

  await page.goto('/landing-demo/feed')
  const feed = page.locator('[data-demo-screen="feed"]')
  await expect(feed).toBeVisible()
  await expect(feed).toHaveAttribute('data-figma-screen', '40:519')
  await feed.getByRole('button', { name: 'Map', exact: true }).click()
  await expect(feed.getByLabel('Interactive map preview')).toBeVisible()
  await feed.getByRole('button', { name: 'Open Maple Grove Park' }).click()
  await expect(page.getByRole('dialog', { name: 'Maple Grove Park details' })).toBeVisible()
  await page.getByRole('button', { name: 'Close details' }).click()
  await feed.locator('.landing-demo-feed-toolbar .landing-demo-segment').getByRole('button', { name: 'Feed', exact: true }).click()
  await feed.getByRole('button', { name: 'Search puddle', exact: true }).click()
  await feed.getByPlaceholder('Search puddle').fill('not-a-puddle')
  await expect(feed.getByText('No puddles found.', { exact: true })).toBeVisible()

  await page.goto('/landing-demo/profile')
  const profile = page.locator('[data-demo-screen="profile"]')
  await expect(profile).toBeVisible()
  await expect(profile).toHaveAttribute('data-figma-screen', '40:347')
  await expect(profile.getByRole('heading', { name: 'Richie Zheng', exact: true })).toBeVisible()
  await profile.getByRole('button', { name: 'Follow', exact: true }).click()
  await expect(profile.getByRole('button', { name: 'Following', exact: true })).toBeVisible()
  await profile.getByRole('button', { name: 'Edit', exact: true }).click()
  await profile.getByRole('textbox', { name: 'Display name' }).fill('Richie Test')
  await profile.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(profile.getByRole('heading', { name: 'Richie Test', exact: true })).toBeVisible()
  await profile.getByRole('button', { name: /Message/ }).click()
  const messageDialog = page.getByRole('dialog', { name: 'Message Richie Zheng' })
  await expect(messageDialog).toBeVisible()
  await expect(messageDialog.getByRole('button', { name: 'Close message' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(messageDialog).toBeHidden()
  await expect(profile.getByRole('button', { name: /Message/ })).toBeFocused()
})

test('landing embeds the Figma phone set for each responsive composition instead of screenshot placeholders', async ({ page }) => {
  await page.setViewportSize({ width: 1281, height: 900 })
  await page.goto('/')
  await page.waitForFunction(() => document.querySelector('.landing-stage--desktop')?.dataset.ready === 'true')

  for (const demo of ['swipe', 'save', 'feed']) {
    const phone = page.locator(`.landing-canvas--desktop [data-phone-demo="${demo}"]`)
    await expect(phone).toBeAttached()
    await expect(phone.locator('iframe')).toHaveAttribute('data-src', `/landing-demo/${demo}`)
  }
  await expect(page.locator('.landing-canvas--desktop [data-phone-demo="profile"]')).toHaveCount(0)

  const swipePhone = page.locator('.landing-canvas--desktop [data-phone-demo="swipe"]')
  await swipePhone.scrollIntoViewIfNeeded()
  const swipeIframe = swipePhone.locator('iframe')
  await expect(swipeIframe).toHaveAttribute('src', '/landing-demo/swipe', { timeout: 15_000 })
  const swipeFrame = swipeIframe.contentFrame()
  await expect(swipeFrame.locator('[data-demo-screen="swipe"]')).toHaveAttribute('data-figma-screen', '40:641')
  await expect(swipeFrame.getByRole('button', { name: 'Save place' })).toBeEnabled()

  await page.setViewportSize({ width: 704, height: 900 })
  await page.goto('/')
  await page.waitForFunction(() => document.querySelector('.landing-stage--mobile')?.dataset.ready === 'true')
  for (const demo of ['swipe', 'save', 'feed']) {
    const phone = page.locator(`.landing-canvas--mobile [data-phone-demo="${demo}"]`)
    await expect(phone).toBeAttached()
    await expect(phone.locator('iframe')).toHaveAttribute('data-src', `/landing-demo/${demo}`)
  }
  await expect(page.locator('.landing-canvas--mobile [data-phone-demo="profile"]')).toHaveCount(0)

  await expect(page.locator('img.feature-phone[data-draggable-phone]')).toHaveCount(0)
})
