import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { createStripeRefund } from '@/lib/stripe/client'
import { isSupabaseConfigured } from '@/lib/supabase/env'

export const runtime='nodejs';export const dynamic='force-dynamic'
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const nullableDate=(value)=>{const text=String(value||'').trim();if(!text)return null;const date=new Date(text);return Number.isNaN(date.getTime())?null:date.toISOString()}
async function dashboard(s,id){const{data,error}=await s.rpc('event_ticketing_dashboard_v1',{target_event:id});if(error)throw error;return data}
export async function POST(request,{params}){if(!isSupabaseConfigured())return NextResponse.json({error:'Ticketing is unavailable.'},{status:503});const{id}=await params;const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:'Sign in.'},{status:401});const b=await request.json().catch(()=>({}));try{let r;if(b.action==='upsert_tier')r=await s.rpc('upsert_ticket_tier_v1',{target_event:id,target_tier:UUID.test(String(b.ticketTypeId||''))?b.ticketTypeId:null,tier_name:String(b.name||'').trim(),tier_description:String(b.description||'').trim()||null,tier_price:Math.floor(Number(b.priceCents||0)),tier_quantity:Math.floor(Number(b.quantityTotal||0)),tier_max_per_order:Math.floor(Number(b.maxPerOrder||6)),tier_customer_limit:Math.floor(Number(b.perCustomerLimit||10)),sales_start_value:nullableDate(b.salesStart),sales_end_value:nullableDate(b.salesEnd)});else if(b.action==='archive_tier')r=await s.rpc('archive_ticket_tier_v1',{target_event:id,target_tier:b.ticketTypeId});else if(b.action==='create_promo')r=await s.rpc('create_promo_code_v1',{target_event:id,code_value:String(b.code||'').trim().toUpperCase(),percent_value:b.percentOff?Math.floor(Number(b.percentOff)):null,amount_value:b.amountOffCents?Math.floor(Number(b.amountOffCents)):null,max_uses:b.maxRedemptions?Math.floor(Number(b.maxRedemptions)):null});else if(b.action==='set_paid_ticketing')r=await s.rpc('set_paid_ticketing_v1',{target_event:id,enabled_value:Boolean(b.enabled)});else if(b.action==='decide_refund'){r=await s.rpc('decide_refund_request_v1',{target_refund:b.refundId,decision_value:b.decision});if(!r.error&&b.decision==='approve'){const refund=await createStripeRefund({chargeId:r.data.stripe_charge_id,amount:r.data.amount_cents,reason:'requested_by_customer',idempotencyKey:b.refundId});const{error}=await createAdminClient().from('refund_requests').update({stripe_refund_id:refund.id,status:'processing',processed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',b.refundId);if(error)throw error}}else throw new Error('Unknown ticketing action.');if(r?.error)throw r.error;return NextResponse.json({ok:true,message:'Ticketing updated.',dashboard:await dashboard(s,id)})}catch(e){return NextResponse.json({error:String(e?.message||'Ticketing could not be updated.').slice(0,240)},{status:400})}}
