import { NextResponse } from 'next/server'
import { requirePrivilegedApi } from '@/lib/auth/privileged'
import { verifyCsrf } from '@/lib/security/csrf'
import { enforceRateLimit } from '@/lib/security/rate-limit'
import { readJsonLimited, safeSecurityError } from '@/lib/security/request'
import { boolean, object, string, uuid } from '@/lib/security/schema'
import { recordSecurityEvent } from '@/lib/security/audit'

export const runtime='nodejs';export const dynamic='force-dynamic'
export async function POST(request){let session;try{if(!verifyCsrf(request))return NextResponse.json({error:'Security token is invalid.'},{status:403});session=await requirePrivilegedApi(['super_admin','support','incident_commander']);const limited=await enforceRateLimit({headers:request.headers,userId:session.user.id,action:'admin_notice_change'});if(!limited.allowed)return NextResponse.json({error:'Too many notice changes. Try again later.'},{status:429,headers:{'retry-after':String(limited.retryAfter||60)}});const body=object(await readJsonLimited(request,16_000));const id=body.id?uuid(body.id,'id'):null;const title=string(body.title,{name:'title',min:3,max:240});const noticeBody=string(body.body,{name:'body',min:3,max:2000});const severity=string(body.severity,{name:'severity',choices:['notice','warning','critical'],max:20});const audience=string(body.audience,{name:'audience',choices:['all','authenticated','hosts','attendees','staff'],max:20});const enabled=boolean(body.enabled,'enabled');const startsAt=body.startsAt?new Date(body.startsAt).toISOString():null;const endsAt=body.endsAt?new Date(body.endsAt).toISOString():null;const{data,error}=await session.supabase.rpc('set_system_notice_v1',{notice_id:id,notice_title:title,notice_body:noticeBody,notice_severity:severity,notice_audience:audience,starts_at_value:startsAt,ends_at_value:endsAt,enabled,request_id_value:limited.requestId});if(error)throw error;await recordSecurityEvent({headers:request.headers,actorId:session.user.id,eventType:'system_notice_changed',severity:severity==='critical'?'high':'notice',targetType:'system_notice',targetId:data,metadata:{audience,enabled}});return NextResponse.json({ok:true,id:data})}catch(error){return NextResponse.json({error:safeSecurityError(error,'The system notice could not be changed.')},{status:error?.status||400})}}
