import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(`../../${path}`, import.meta.url), 'utf8')

test('Google Place ID matching exhausts free rich SKUs while parallel discovery remains no-cost', async () => {
  const workflow = await read('.github/workflows/google-place-match.yml')
  const discoveryWorkflow = await read('.github/workflows/google-place-discovery.yml')
  const geocodeWorkflow = await read('.github/workflows/google-place-geocode.yml')
  const matcher = await read('scripts/match-google-places.mjs')
  const discovery = await read('scripts/discover-google-place-ids.mjs')
  const geocoder = await read('scripts/repair-google-place-addresses.mjs')
  const migration = await read('supabase/migrations/10054_google_place_matching_architecture.sql')
  const progression = await read('supabase/migrations/10055_google_place_matching_stage_progression.sql')

  assert.match(workflow, /cron: '29 \* \* \* \*'/)
  assert.match(workflow, /--limit=2000 --apply/)
  assert.match(workflow, /GOOGLE_PLACE_MATCH_DELAY_MS: '100'/)
  assert.match(workflow, /GOOGLE_PLACE_MATCH_MAX_DETAILS_CANDIDATES: '5'/)
  assert.match(workflow, /concurrency:[\s\S]*google-place-id-matching/)
  assert.match(workflow, /10055_google_place_matching_stage_progression\.sql/)
  assert.match(workflow, /GOOGLE_PLACES_API_KEY/)
  assert.doesNotMatch(workflow, /B2_/)

  assert.match(matcher, /'X-Goog-FieldMask': 'places\.id,places\.displayName,places\.formattedAddress,places\.location,places\.primaryType,places\.types'/)
  assert.match(matcher, /'X-Goog-FieldMask': 'places\.id'/)
  assert.match(matcher, /'id,displayName,formattedAddress,location,primaryType,types'/)
  assert.match(matcher, /'id,formattedAddress,location'/)
  assert.match(matcher, /places:searchNearby/)
  assert.match(matcher, /includedPrimaryTypes/)
  assert.match(matcher, /rankPreference: 'DISTANCE'/)
  assert.match(matcher, /SKU\.NEARBY_SEARCH_PRO/)
  assert.match(matcher, /reserve_google_places_free_sku_v1/)
  assert.match(matcher, /release_google_places_free_sku_v1/)
  assert.match(matcher, /claim_google_place_candidates_v3/)
  assert.match(matcher, /scoreGooglePlaceEssentialsMatch/)
  assert.match(matcher, /scoreGoogleNearbyPlaceMatch/)
  assert.match(matcher, /status: 'quota_deferred'/)
  assert.match(matcher, /from\('location_google_places'\)\.upsert/)
  assert.match(matcher, /status: 'verified'/)
  assert.doesNotMatch(matcher, /static-media-overlay|syncStaticMediaOverlayForLocations/)

  assert.match(discoveryWorkflow, /cron: '7 \* \* \* \*'/)
  assert.match(discoveryWorkflow, /google-place-id-discovery/)
  assert.match(discoveryWorkflow, /locations:google:discover/)
  assert.match(discovery, /'X-Goog-FieldMask': 'places\.id'/)
  assert.match(discovery, /googleIdsOnlyQueryVariants/)
  assert.match(discovery, /record_google_place_id_candidate_v1/)
  assert.doesNotMatch(discovery, /reserve_google_places_free_sku_v1/)

  assert.match(geocodeWorkflow, /cron: '43 \* \* \* \*'/)
  assert.match(geocodeWorkflow, /google-place-address-repair/)
  assert.match(geocoder, /maps\.googleapis\.com\/maps\/api\/geocode\/json/)
  assert.match(geocoder, /target_sku: GEOCODING_SKU/)
  assert.match(geocoder, /addressOverride: geocode\.address/)
  assert.doesNotMatch(geocoder, /address_public\s*:/)

  assert.match(migration, /'text_search_pro' then 5000/)
  assert.match(migration, /'place_details_pro' then 5000/)
  assert.match(migration, /'place_details_essentials' then 10000/)
  assert.match(migration, /'autocomplete_requests' then 10000/)
  assert.match(migration, /'nearby_search_pro' then 5000/)
  assert.match(migration, /'geocoding' then 10000/)
  assert.match(migration, /America\/Los_Angeles/)
  assert.match(migration, /create table if not exists public\.google_place_id_candidates/)
  assert.match(migration, /create table if not exists public\.google_place_geocode_attempts/)
  assert.match(migration, /claim_google_place_candidates_v3/)
  assert.match(migration, /claim_google_place_discovery_candidates_v1/)
  assert.match(migration, /claim_google_place_geocode_candidates_v1/)
  assert.match(migration, /grant execute on function public\.reserve_google_places_free_sku_v1\(text\) to service_role/)

  assert.match(progression, /claim_google_place_candidates_v3/)
  assert.match(progression, /attempt\.status='no_match'/)
  assert.match(progression, /interval '6 hours'/)
})

test('Discover prefers a stored Google Place ID and only uses coordinates when no ID exists', async () => {
  const discovery = await read('lib/app/discovery-relational.js')

  assert.match(discovery, /const googlePlaceId = row\.google_place_id \|\| null/)
  assert.match(discovery, /const googleClientLookup = !photoUrl && !googlePlaceId/)
  assert.match(discovery, /google_photo_proxy_url: googlePlaceId \?/)
})
