import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(`../../${path}`, import.meta.url), 'utf8')

test('global photo materialization runs hourly and can be dispatched manually', async () => {
  const workflow = await read('.github/workflows/global-photo-enrichment.yml')
  const overlayWorkflow = await read('.github/workflows/publish-b2-photo-overlay.yml')
  assert.match(workflow, /workflow_dispatch:/)
  assert.match(workflow, /\bschedule:/)
  assert.match(workflow, /cron: '31 \* \* \* \*'/)
  assert.match(workflow, /group: global-photo-enrichment-\$\{\{ inputs\.countries \|\| 'all' \}\}/)
  assert.doesNotMatch(workflow, /materialize_limit/)
  assert.doesNotMatch(workflow, /--limit=/)
  assert.match(workflow, /timeout-minutes: 360/)
  assert.match(workflow, /cancel-in-progress: false/)
  assert.match(overlayWorkflow, /workflow_dispatch:/)
  assert.match(overlayWorkflow, /group: b2-photo-overlay-publish/)
  assert.match(overlayWorkflow, /build_b2_photo_search_overlay\.py/)
  assert.doesNotMatch(overlayWorkflow, /materialize_photo_candidates\.py/)
})

test('global photo enrichment builds candidates from the active canonical snapshot', async () => {
  const workflow = await read('.github/workflows/global-photo-enrichment.yml')
  assert.match(workflow, /python scripts\/global-data\/active_snapshot\.py/)
  assert.match(workflow, /build_wikimedia_candidates\.py/)
  assert.match(workflow, /build_mapillary_candidates\.py/)
  assert.match(workflow, /steps\.active\.outputs\.snapshot/)
})

test('the immutable location rebuild carries active canonical photo state forward before indexing', async () => {
  const workflow = await read('.github/workflows/global-location-data.yml')
  const carrier = await read('scripts/global-data/carry_photo_enrichment.py')

  assert.match(workflow, /id: active/)
  assert.match(workflow, /active_snapshot\.py/)
  assert.match(workflow, /carry_photo_enrichment\.py/)
  assert.ok(workflow.indexOf('carry_photo_enrichment.py') < workflow.indexOf('build_bootstrap_overlays.py'))
  assert.ok(workflow.indexOf('build_bootstrap_overlays.py') < workflow.indexOf('build_b2_search_index.py'))
  assert.ok(workflow.indexOf('validate_b2_search_index.py --snapshot') < workflow.lastIndexOf('build_b2_photo_search_overlay.py'))
  assert.match(carrier, /photo_metadata/)
  assert.match(carrier, /photo_exclusions/)
  assert.match(carrier, /copy_object/)
  assert.match(carrier, /source-snapshot/)
  assert.match(carrier, /target-snapshot/)
})

test('selected licensed photos materialize directly into immutable B2 media', async () => {
  const workflow = await read('.github/workflows/global-photo-enrichment.yml')
  const materializer = await read('scripts/global-data/materialize_photo_candidates.py')
  const overlayBuilder = await read('scripts/global-data/build_b2_photo_search_overlay.py')
  assert.match(workflow, /B2_MEDIA_OPEN_PHOTO_PREFIX/)
  assert.match(workflow, /media\/photos\/by-sha256/)
  assert.match(workflow, /materialize_photo_candidates\.py/)
  assert.match(materializer, /sha256/i)
  assert.match(materializer, /B2_MEDIA_OPEN_PHOTO_PREFIX/)
  assert.doesNotMatch(materializer, /parser\.add_argument\('--limit'/)
  assert.doesNotMatch(materializer, /\bLIMIT\s*=/)
  assert.doesNotMatch(materializer, /min\(10_000|min\(100_000/)
  assert.match(materializer, /for grouped in candidate_batches\(query(?:, country_location_limit)?\)/)
  assert.match(materializer, /CREATE TEMP TABLE photo_candidate_queue AS/)
  assert.match(materializer, /WHERE location_id > '\{escaped_cursor\}'/)
  assert.match(materializer, /row_number\(\) OVER/)
  assert.match(materializer, /photo candidate queue ready/)
  assert.match(materializer, /photo_attempts/)
  assert.match(materializer, /retryable_error/)
  assert.match(materializer, /HTTP_POOL/)
  assert.match(materializer, /redirect=False/)
  assert.match(materializer, /MAX_SOURCE_PIXELS/)
  assert.match(workflow, /build_b2_photo_search_overlay\.py/)
  assert.ok(workflow.indexOf('materialize_photo_candidates.py') < workflow.indexOf('build_b2_photo_search_overlay.py'))
  assert.match(workflow, /pip install[^\n]*brotli[^\n]*orjson/)
  assert.match(overlayBuilder, /photo-overlay-v1/)
  assert.match(overlayBuilder, /CacheControl.*immutable/)
  assert.match(overlayBuilder, /CacheControl=.*no-store/)
  assert.doesNotMatch(overlayBuilder, /delete_object|delete_objects/i)
})

test('canonical B2 photo inventory audit is read-only and checks byte identity', async () => {
  const workflow = await read('.github/workflows/audit-b2-photo-inventory.yml')
  const audit = await read('scripts/global-data/audit_b2_photo_inventory.py')

  assert.match(workflow, /workflow_dispatch:/)
  assert.match(workflow, /schedule:/)
  assert.match(workflow, /audit_b2_photo_inventory\.py/)
  assert.match(workflow, /upload-artifact@v7/)
  assert.match(audit, /list_objects_v2/)
  assert.match(audit, /head_object/)
  assert.match(audit, /get_object/)
  assert.match(audit, /hashlib\.sha256/)
  assert.match(audit, /Image\.open/)
  assert.match(audit, /MAX_SOURCE_PIXELS/)
  assert.match(audit, /photo_metadata/)
  assert.ok(audit.lastIndexOf('metadata = read_active_photo_metadata(') < audit.lastIndexOf('media_objects = list_objects('))
  assert.doesNotMatch(audit, /(?:put|copy|delete)_object|upload_file|supabase_rpc/i)
})

test('broken B2 photo references are excluded durably without deleting media', async () => {
  const workflow = await read('.github/workflows/repair-b2-photo-references.yml')
  const repair = await read('scripts/global-data/repair_b2_photo_references.py')
  const overlay = await read('scripts/global-data/build_b2_photo_search_overlay.py')

  assert.match(workflow, /workflow_dispatch:/)
  assert.match(workflow, /type: boolean/)
  assert.match(workflow, /repair_b2_photo_references\.py/)
  assert.match(workflow, /inputs\.apply/)
  assert.match(workflow, /build_b2_photo_search_overlay\.py/)
  assert.match(workflow, /pip install[^\n]*brotli[^\n]*orjson/)
  assert.match(repair, /canonical_media_hashes/)
  assert.match(repair, /missing_canonical_object/)
  assert.match(repair, /repair-missing-canonical-v1\.parquet/)
  assert.match(repair, /put_object/)
  assert.match(repair, /objectsRemoved.*0/)
  assert.doesNotMatch(repair, /delete_object|delete_objects|remove_objects/i)
  assert.match(overlay, /list_canonical_media_hashes/)
  assert.match(overlay, /JOIN canonical_media_hashes/)
  assert.match(overlay, /refusing to publish an empty overlay/)
})

test('canonical B2 metadata repair is byte-preserving and never deletes inventory', async () => {
  const workflow = await read('.github/workflows/repair-b2-photo-inventory.yml')
  const repair = await read('scripts/global-data/repair_b2_photo_inventory.py')

  assert.match(workflow, /workflow_dispatch:/)
  assert.match(workflow, /inputs:\s+apply:/)
  assert.match(workflow, /repair_b2_photo_inventory\.py/)
  assert.match(repair, /hashlib\.sha256/)
  assert.match(repair, /Image\.open/)
  assert.match(repair, /copy_object/)
  assert.match(repair, /MetadataDirective.*REPLACE/)
  assert.match(repair, /objectsRemoved.*0/)
  assert.doesNotMatch(repair, /delete_object|delete_objects|remove\(/i)
})

test('the three previously implicit table-access decisions are encoded in migration', async () => {
  const migration = await read('supabase/migrations/20260826190000_intentional_rls_for_internal_tables.sql')
  const applyWorkflow = await read('.github/workflows/apply-internal-table-rls.yml')

  for (const table of ['location_save_counts', 'location_save_density_tiles', 'spatial_ref_sys']) {
    if (table !== 'spatial_ref_sys') assert.match(migration, new RegExp(`alter table if exists public\\.${table} enable row level security`))
  }
  assert.match(migration, /location_save_counts_service_role_all/)
  assert.match(migration, /location_save_density_tiles_service_role_all/)
  assert.match(migration, /to_regclass\('public\.location_save_counts'\)/)
  assert.match(migration, /to_regclass\('public\.location_save_density_tiles'\)/)
  assert.match(migration, /spatial_ref_sys_read/)
  assert.match(migration, /table_owner=current_user or coalesce\(migration_role_is_superuser,false\)/)
  assert.match(migration, /spatial_ref_sys is extension-owned/)
  assert.match(migration, /revoke insert, update, delete, truncate, references, trigger[\s\S]*spatial_ref_sys/)
  assert.match(migration, /grant select on table public\.spatial_ref_sys to public/)
  assert.match(applyWorkflow, /SUPABASE_ACCESS_TOKEN/)
  assert.match(applyWorkflow, /supabase db query/)
  assert.match(applyWorkflow, /20260826190000_intentional_rls_for_internal_tables\.sql/)
})

test('materializer tolerates pre-B2 bootstrap photo metadata without content hashes', async () => {
  const materializer = await read('scripts/global-data/materialize_photo_candidates.py')
  assert.match(materializer, /DESCRIBE SELECT \* FROM read_parquet/)
  assert.match(materializer, /'content_hash' in bootstrap_columns/)
  assert.match(materializer, /ignoring legacy bootstrap photo metadata without content_hash/)
  assert.match(materializer, /'content_hash' in enriched_columns/)
})

test('retired relational photo enrichment is not part of the production pipeline', async () => {
  const repositoryCheck = await read('scripts/check.mjs')
  const packageJson = JSON.parse(await read('package.json'))
  assert.match(repositoryCheck, /scripts\/enrich-open-location-photos\.mjs/)
  assert.match(repositoryCheck, /\.github\/workflows\/photo-enrichment\.yml/)
  assert.equal(packageJson.scripts?.['locations:photos'], undefined)
  assert.equal(packageJson.scripts?.['locations:photos:migrate-b2'], undefined)
})

test('provider rate limits match upstream contracts', async () => {
  const materializeWorkflow = await read('.github/workflows/global-photo-enrichment.yml')
  const materializer = await read('scripts/global-data/materialize_photo_candidates.py')
  const wikimediaWorkflow = await read('.github/workflows/global-wikimedia-enrichment.yml')
  const wikimedia = await read('scripts/global-data/build_wikimedia_candidates.py')
  const mapillaryWorkflow = await read('.github/workflows/global-mapillary-enrichment.yml')
  const mapillary = await read('scripts/global-data/build_mapillary_candidates.py')
  const kartaWorkflow = await read('.github/workflows/global-kartaview-enrichment.yml')
  const karta = await read('scripts/global-data/build_kartaview_candidates.py')
  const kartaUrls = await read('scripts/global-data/kartaview_urls.py')

  assert.match(materializeWorkflow, /GLOBAL_PHOTO_DOWNLOAD_CONCURRENCY: '192'/)
  assert.match(materializeWorkflow, /GLOBAL_PHOTO_WIKIMEDIA_DOWNLOAD_CONCURRENCY: '2'/)
  assert.match(materializeWorkflow, /GLOBAL_PHOTO_WIKIMEDIA_DOWNLOAD_MBIT: '25'/)
  assert.match(materializeWorkflow, /MAPILLARY_GRAPH_REQUESTS_PER_MINUTE: '50000'/)
  assert.match(materializer, /WIKIMEDIA_DOWNLOAD_CONCURRENCY/)
  assert.match(materializer, /WIKIMEDIA_DOWNLOAD_MBIT/)
  assert.match(materializer, /MAPILLARY_GRAPH_REQUESTS_PER_MINUTE/)
  assert.match(materializer, /'access_token': MAPILLARY_TOKEN/)
  assert.match(materializer, /Retry-After/)

  assert.match(wikimediaWorkflow, /WIKIMEDIA_REQUESTS_PER_MINUTE: '200'/)
  assert.match(wikimediaWorkflow, /WIKIMEDIA_RUN_BUDGET_SECONDS: '14400'/)
  assert.match(wikimediaWorkflow, /WIKIMEDIA_REQUEST_LIMIT: \$\{\{ vars\.WIKIMEDIA_REQUEST_LIMIT \|\| '48000' \}\}/)
  assert.match(wikimedia, /min\(200, int\(os\.getenv\('WIKIMEDIA_REQUESTS_PER_MINUTE'/)
  assert.match(wikimedia, /3 if ACCESS_TOKEN else 1/)
  assert.match(wikimedia, /'iiurlwidth': '1600'/)
  assert.match(wikimedia, /'Accept-Encoding': 'gzip'/)
  assert.match(wikimedia, /gate\.defer\(5\.0\)/)
  assert.match(wikimedia, /RUN_BUDGET_SECONDS/)
  assert.match(wikimedia, /runtime_budget_exhausted/)

  assert.match(mapillaryWorkflow, /default: '50000'/)
  assert.match(mapillaryWorkflow, /MAPILLARY_TILE_DAILY_LIMIT: '50000'/)
  assert.match(mapillary, /DAILY_REQUEST_LIMIT = max\(1, min\(50_000/)
  assert.match(mapillary, /reserve_daily_budget/)
  assert.match(mapillary, /release_unused_budget/)
  assert.match(mapillary, /permanent:unexpected content type/)
  assert.match(mapillary, /permanent:decode/)

  assert.match(kartaWorkflow, /default: '1000'/)
  assert.match(kartaWorkflow, /KARTAVIEW_REQUESTS_PER_HOUR: '1000'/)
  assert.match(kartaWorkflow, /KARTAVIEW_MAX_CONCURRENCY: '8'/)
  assert.match(kartaWorkflow, /KARTAVIEW_RUN_BUDGET_SECONDS: '3900'/)
  assert.match(kartaWorkflow, /KARTAVIEW_CHECKPOINT_EVERY: '100'/)
  assert.match(karta, /PROVIDER_HOURLY_MAX = 1000 if TOKEN else 100/)
  assert.match(karta, /START_INTERVAL = 3600\.0 \/ REQUESTS_PER_HOUR/)
  assert.match(karta, /Retry-After/)
  assert.match(karta, /RUN_BUDGET_SECONDS/)
  assert.match(karta, /CHECKPOINT_EVERY/)
  assert.match(karta, /attempted_since_checkpoint/)
  assert.match(karta, /from kartaview_urls import asset_url/)
  assert.match(kartaUrls, /imageProcUrl/)
  assert.match(kartaUrls, /cdn\.kartaview\.org\/pr:sharp/)
  assert.match(kartaUrls, /\{\{sizeprefix\}\}/)
  assert.match(kartaUrls, /urlsafe_b64encode/)
  assert.match(materializer, /from kartaview_urls import canonical_asset_url/)
  assert.match(materializer, /provider == 'kartaview'/)
  assert.match(materializer, /status in \{'exhausted', 'invalid'\}/)
  assert.match(materializer, /'retryable': retryable/)

  assert.match(materializer, /RUN_BUDGET_SECONDS/)
  assert.match(materializer, /runtimeBudgetExhausted/)
  assert.match(materializeWorkflow, /GLOBAL_PHOTO_RUN_BUDGET_SECONDS: '19800'/)
})
