import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const cardSource = await readFile(new URL('../../components/figma-swipe-card.js', import.meta.url), 'utf8')
const workspaceSource = await readFile(new URL('../../components/date-swipe-workspace-v2.js', import.meta.url), 'utf8')
const shellCss = await readFile(new URL('../../app/figma-dashboard-rebuild.css', import.meta.url), 'utf8')
const swipeCss = await readFile(new URL('../../app/figma-dashboard-swipe.css', import.meta.url), 'utf8')

test('rebuilt Figma swipe card uses viewport exit geometry and a concurrent card stack', () => {
  assert.match(cardSource, /export function FigmaSwipeCard/)
  assert.match(cardSource, /className=\{`figma-swipe-card/)
  assert.match(cardSource, /choiceInFlight/)
  assert.match(cardSource, /actionRequest\?\.id/)
  assert.match(cardSource, /const cardRef = useRef\(null\)/)
  assert.match(cardSource, /function exitOffset\(direction\)/)
  assert.match(cardSource, /getBoundingClientRect\(\)/)
  assert.match(cardSource, /Math\.hypot\(rect\.width, rect\.height\)/)
  assert.match(cardSource, /window\.innerWidth/)
  assert.doesNotMatch(cardSource, /Math\.max\(-180, Math\.min\(180/)
  assert.doesNotMatch(cardSource, /-720|720/)
  assert.match(cardSource, /preview = false/)
  assert.match(cardSource, /is-preview/)
  assert.match(cardSource, /is-leaving/)
  assert.match(cardSource, /prefers-reduced-motion: reduce/)
  assert.match(cardSource, /function preventNativeImageDrag\(event\)/)
  assert.match(cardSource, /draggable=\{false\}/)
  assert.match(cardSource, /onDragStart=\{preventNativeImageDrag\}/)
  assert.match(cardSource, /function pointerCancel\(event\)/)
  assert.match(cardSource, /onPointerCancel=\{pointerCancel\}/)
  assert.doesNotMatch(cardSource, /onPointerCancel=\{pointerUp\}/)
  assert.match(cardSource, /onLostPointerCapture=\{pointerCancel\}/)
  assert.match(cardSource, /event\.button !== 0 \|\| !event\.isPrimary/)
  assert.match(cardSource, /if \(delta <= -90\) choose\('pass'\)/)
  assert.match(cardSource, /else if \(delta >= 90\) choose\('save'\)/)
  assert.match(cardSource, /event\.key === 'ArrowLeft'\) \{ event\.preventDefault\(\); choose\('pass'\) \}/)
  assert.match(cardSource, /event\.key === 'ArrowRight'\) \{ event\.preventDefault\(\); choose\('save'\) \}/)
  assert.match(cardSource, /await onChoice\(action, item\)/)

  assert.match(workspaceSource, /import \{ FigmaSwipeCard \}/)
  assert.match(workspaceSource, /const next = feed\.items\[index \+ 1\]/)
  assert.match(workspaceSource, /key=\{`preview:\$\{next\.content_id\}`\} item=\{next\} preview/)
  assert.match(workspaceSource, /onLeavingChange=\{setCardLeaving\}/)
  assert.match(workspaceSource, /onActionHandled=\{clearActionRequest\}/)
  assert.match(workspaceSource, /onSave=\{\(\) => requestChoice\('save'\)\}/)
  assert.match(workspaceSource, /onPass=\{\(\) => requestChoice\('pass'\)\}/)
  assert.match(workspaceSource, /if \(event\.key === 'ArrowRight'\) requestChoice\('save'\)/)
  assert.match(workspaceSource, /const persistedAction = action === 'pass' \? 'dismissed' : action === 'perfect' \? 'perfect' : 'saved'/)
  assert.match(workspaceSource, /queueDiscoveryAction\(\{/)
  assert.match(workspaceSource, /actionRequest=\{actionRequest\}/)
  assert.doesNotMatch(workspaceSource, /MinimalSwipePreviewCard/)

  assert.match(shellCss, /\.figma-swipe-card-stage\s*\{/)
  assert.match(shellCss, /width: 400px/)
  assert.match(shellCss, /height: 560px/)
  assert.match(shellCss, /transition: transform \.28s ease, opacity \.2s ease/)
  assert.match(swipeCss, /\.figma-swipe-actions\s*\{/)
  assert.match(swipeCss, /top: 666px/)
  assert.match(swipeCss, /grid-template-columns: repeat\(4, 1fr\)/)
})
