async function queryOr(query, fallback = []) {
  try {
    const { data, error } = await query
    return error ? fallback : data || fallback
  } catch {
    return fallback
  }
}

function itemFromState(row) {
  if (row.event_id && row.events) return { kind: 'event', id: row.event_id, state: row.state, title: row.events.title, slug: row.events.slug, summary: row.events.summary, startsAt: row.events.starts_at, href: `/events/${row.events.slug}` }
  if (row.location_id && row.locations) return { kind: 'place', id: row.location_id, state: row.state, title: row.locations.name, slug: row.locations.slug, summary: row.locations.summary, city: row.locations.city, href: `/places/${row.locations.slug}` }
  return null
}

export async function getPlansSnapshot({ supabase, user }) {
  const [states, rsvps, visits, hostMemberships, permissions, plans, tickets] = await Promise.all([
    queryOr(supabase.from('user_content_states').select('state,event_id,location_id,created_at,events(id,title,slug,summary,starts_at,ends_at,status),locations(id,name,slug,summary,city,status)').eq('profile_id', user.id).order('created_at', { ascending: false })),
    queryOr(supabase.from('event_rsvps').select('event_id,status,visibility,guest_count,waitlist_position,created_at,events(id,title,slug,summary,starts_at,ends_at,status,capacity,cover_path,locations(name,city))').eq('profile_id', user.id).order('created_at', { ascending: false })),
    queryOr(supabase.from('location_visits').select('location_id,status,planned_for,visited_at,note,locations(id,name,slug,summary,city,cover_path)').eq('profile_id', user.id).order('created_at', { ascending: false })),
    queryOr(supabase.from('host_members').select('host_profile_id').eq('profile_id', user.id).not('accepted_at', 'is', null)),
    queryOr(supabase.from('event_permissions').select('event_id').eq('profile_id', user.id)),
    queryOr(supabase.from('plan_members').select('role,status,plan_id,plans(id,title,description,city,starts_at,ends_at,timezone,visibility,status,meeting_label,owner_id,created_at)').eq('profile_id', user.id).in('status', ['invited','accepted']).order('invited_at', { ascending: false }).limit(100)),
    queryOr(supabase.from('tickets').select('id,status,ticket_number,created_at,ticket_types(name,events(id,title,slug,starts_at))').eq('owner_id', user.id).order('created_at', { ascending: false }))
  ])
  const hostIds=hostMemberships.map(item=>item.host_profile_id).filter(Boolean),permissionIds=permissions.map(item=>item.event_id).filter(Boolean);let hosting=[];const filters=[`created_by.eq.${user.id}`];if(hostIds.length)filters.push(`host_profile_id.in.(${hostIds.join(',')})`);if(permissionIds.length)filters.push(`id.in.(${permissionIds.join(',')})`);if(filters.length)hosting=await queryOr(supabase.from('events').select('id,title,slug,summary,starts_at,ends_at,status,capacity,host_profile_id,locations(name,city)').or(filters.join(',')).order('starts_at',{ascending:true}).limit(100));const stateItems=states.map(itemFromState).filter(Boolean);const savedEvents=stateItems.filter(item=>item.state==='saved'&&item.kind==='event');const plannedPlaceItems=visits.filter(v=>v.status==='planned').map(v=>({kind:'place',id:v.location_id,state:'planned',title:v.locations?.name,slug:v.locations?.slug,summary:v.note||v.locations?.summary,city:v.locations?.city,plannedFor:v.planned_for,href:v.locations?.slug?`/places/${v.locations.slug}`:'/explore'}));const savedPlaceMap=new Map(stateItems.filter(item=>item.state==='saved'&&item.kind==='place').map(item=>[item.id,item]));for(const item of plannedPlaceItems)savedPlaceMap.set(item.id,{...(savedPlaceMap.get(item.id)||{}),...item});const savedPlaces=[...savedPlaceMap.values()];const interested=stateItems.filter(item=>item.state==='interested');const going=rsvps.filter(item=>['going','checked_in','requested','waitlisted'].includes(item.status));const past=[...stateItems.filter(item=>item.state==='visited'),...visits.filter(item=>item.status==='visited').map(v=>({kind:'place',id:v.location_id,title:v.locations?.name,slug:v.locations?.slug,summary:v.note||v.locations?.summary,visitedAt:v.visited_at,href:v.locations?.slug?`/places/${v.locations.slug}`:'/explore'}))];return{savedEvents,savedPlaces,interested,going,tickets,hosting,sharedPlans:plans.map(m=>({...(m.plans||{}),membership_status:m.status,membership_role:m.role})).filter(p=>p.id),past,plannedVisits:visits.filter(v=>v.status==='planned'),counts:{saved_events:savedEvents.length,saved_places:savedPlaces.length,interested:interested.length,going:going.length,tickets:tickets.length,hosting:hosting.length,shared:plans.filter(m=>m.plans).length,past:past.length}}
}

export async function getPlanDetail({ supabase, user }, id) {
  const [planResult,members,availability,stops,polls,messages,events,locations]=await Promise.all([supabase.from('plans').select('*').eq('id',id).maybeSingle(),queryOr(supabase.from('plan_members').select('profile_id,role,status,invited_at,responded_at,profiles(display_name,username,avatar_path)').eq('plan_id',id).order('invited_at')),queryOr(supabase.from('plan_availability').select('id,profile_id,starts_at,ends_at,note,profiles(display_name,username)').eq('plan_id',id).order('starts_at')),queryOr(supabase.from('plan_stops').select('id,event_id,location_id,position,planned_for,duration_minutes,note,meeting_label,events(id,title,slug,summary,starts_at,ends_at),locations(id,name,slug,summary,city)').eq('plan_id',id).order('position')),queryOr(supabase.from('plan_polls').select('id,question,status,closes_at,created_at,plan_poll_options(id,label,event_id,location_id,sort_order,events(title,slug),locations(name,slug),plan_votes(profile_id,choice,rank))').eq('plan_id',id).order('created_at',{ascending:false})),queryOr(supabase.from('plan_messages').select('id,sender_id,body,created_at,edited_at,profiles(display_name,username)').eq('plan_id',id).is('deleted_at',null).order('created_at').limit(200)),queryOr(supabase.from('events').select('id,title,slug,starts_at').eq('status','published').order('starts_at').limit(60)),queryOr(supabase.from('locations').select('id,name,slug,city').eq('status','published').order('name').limit(60))]);if(planResult.error||!planResult.data)return null;return{plan:planResult.data,members,availability,stops,polls,messages,events,locations,currentUserId:user.id}
}
