"use server"
import { redirect } from 'next/navigation'
import { requireUser } from '@/lib/auth/user'
import { pathWithMessage,safeNextPath } from '@/lib/auth/redirect'
const clean=(v,n=5000)=>String(v||'').trim().slice(0,n)
const checked=(f,n)=>['on','true'].includes(String(f.get(n)))
const next=(f,d)=>safeNextPath(clean(f.get('next'),500)||d)
async function rpc(f,name,args,fallback,message){const s=await requireUser({onboarding:true});const dest=next(f,fallback);const r=await s.supabase.rpc(name,args);if(r.error)redirect(pathWithMessage(dest,'error','That action could not be completed.'));return{...r,dest,message}}
export async function sendFriendRequest(f){const r=await rpc(f,'send_friend_request_v1',{target:clean(f.get('profile_id'),36)},'/friends','Friend request sent.');redirect(pathWithMessage(r.dest,'success',r.data==='accepted'?'You are now friends.':r.message))}
export async function respondFriendRequest(f){const r=await rpc(f,'respond_friend_request_v1',{target:clean(f.get('profile_id'),36),response:clean(f.get('response'),20)},'/friends','Friend request updated.');redirect(pathWithMessage(r.dest,'success',r.message))}
export async function removeFriend(f){const r=await rpc(f,'remove_friend_v1',{target:clean(f.get('profile_id'),36)},'/friends','Friend removed.');redirect(pathWithMessage(r.dest,'success',r.message))}
export async function setCloseFriend(f){const enabled=clean(f.get('enabled'),10)==='true';const r=await rpc(f,'set_close_friend_v1',{target:clean(f.get('profile_id'),36),enabled},'/friends',enabled?'Added to close friends.':'Removed from close friends.');redirect(pathWithMessage(r.dest,'success',r.message))}
export async function blockProfile(f){const r=await rpc(f,'block_profile_v1',{target:clean(f.get('profile_id'),36)},'/friends','Profile blocked.');redirect(pathWithMessage(r.dest,'success',r.message))}
export async function unblockProfile(f){const r=await rpc(f,'unblock_profile_v1',{target:clean(f.get('profile_id'),36)},'/friends','Profile unblocked.');redirect(pathWithMessage(r.dest,'success',r.message))}
export async function followHost(f){const enabled=clean(f.get('enabled'),10)!=='false';const r=await rpc(f,'follow_host_v1',{target:clean(f.get('host_id'),36),enabled},'/friends',enabled?'Host followed.':'Host unfollowed.');redirect(pathWithMessage(r.dest,'success',r.message))}
export async function openDirectConversation(f){const r=await rpc(f,'open_direct_conversation_v1',{target:clean(f.get('profile_id'),36)},'/inbox','');redirect(`/inbox/${r.data}`)}
export async function openSupportConversation(f){const r=await rpc(f,'open_support_conversation_v1',{},'/inbox','');redirect(`/inbox/${r.data}`)}
export async function saveSocialPrivacy(f){const s=await requireUser({onboarding:true});const v=clean(f.get('activity_visibility'),20);const{error}=await s.supabase.from('profiles').update({activity_visibility:['private','close_friends','friends','public'].includes(v)?v:'friends',allow_friend_requests:checked(f,'allow_friend_requests'),allow_event_messages:checked(f,'allow_event_messages')}).eq('id',s.user.id);redirect(pathWithMessage('/friends',error?'error':'success',error?'Privacy settings could not be saved.':'Privacy settings saved.'))}
export async function shareContent(f){const s=await requireUser({onboarding:true});const dest=next(f,'/discover');const username=clean(f.get('username'),24).replace(/^@/,'');const{data:recipient}=await s.supabase.rpc('friend_profile_by_username_v1',{target_username:username});if(!recipient)redirect(pathWithMessage(dest,'error','That accepted friend could not be found.'));const{error}=await s.supabase.rpc('share_content_v1',{target_kind:clean(f.get('kind'),20),target_id:clean(f.get('content_id'),36),recipient_profile:recipient,target_plan:null,share_note:clean(f.get('note'),1000)||null});redirect(pathWithMessage(dest,error?'error':'success',error?'That item could not be shared.':'Shared with your friend.'))}
export async function createComment(f){const s=await requireUser({onboarding:true});const dest=next(f,'/discover');const{error}=await s.supabase.rpc('create_social_comment_v1',{target_kind:clean(f.get('kind'),20),target_id:clean(f.get('content_id'),36),comment_body:clean(f.get('body'),2000),parent_comment:Number(f.get('parent_id'))||null});redirect(pathWithMessage(dest,error?'error':'success',error?'Comment could not be posted.':'Comment posted.'))}
export async function markNotificationRead(f){const s=await requireUser({onboarding:true});await s.supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',Number(f.get('notification_id'))).eq('profile_id',s.user.id);redirect(next(f,'/notifications'))}
export async function markAllNotificationsRead(){const s=await requireUser({onboarding:true});await s.supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('profile_id',s.user.id).is('read_at',null);redirect('/notifications')}
export async function saveNotificationPreferences(f){const s=await requireUser({onboarding:true});const values={profile_id:s.user.id};for(const k of['in_app_enabled','email_enabled','friend_requests','shares','messages','comments','event_reminders','event_changes','host_announcements','marketing'])values[k]=checked(f,k);values.quiet_start=clean(f.get('quiet_start'),8)||null;values.quiet_end=clean(f.get('quiet_end'),8)||null;values.timezone=clean(f.get('timezone'),80)||'America/Toronto';values.updated_at=new Date().toISOString();const{error}=await s.supabase.from('notification_preferences').upsert(values);redirect(pathWithMessage('/notifications',error?'error':'success',error?'Preferences could not be saved.':'Notification preferences saved.'))}
export async function sendHostAnnouncement(f){const r=await rpc(f,'send_host_announcement_v1',{target_host:clean(f.get('host_id'),36),target_event:clean(f.get('event_id'),36)||null,announcement_title:clean(f.get('title'),160),announcement_body:clean(f.get('body'),1000)},'/notifications','Announcement sent.');redirect(pathWithMessage(r.dest,'success',r.message))}
