-- Stage 9C: rate-limit enforcement, media scan workers, privileged actions, dashboards, and anomaly foundations.
create or replace function public.consume_security_rate_limit_v1(actor_id_value uuid,action_name_value text,ip_hash_value text,device_hash_value text,host_id_value uuid,request_weight integer,request_id_value text) returns jsonb language plpgsql security definer set search_path=public as $$
declare rule public.rate_limit_rules%rowtype;dimension_value text;window_start timestamptz;counter public.rate_limit_counters%rowtype;allowed boolean:=true;retry integer:=0;limits jsonb:='[]'::jsonb;
begin
  for rule in select * from public.rate_limit_rules where active and (rate_limit_rules.action_name=action_name_value or rate_limit_rules.action_name='*') loop
    dimension_value:=case rule.dimension_type when 'ip' then ip_hash_value when 'user' then coalesce(actor_id_value::text,'anonymous') when 'device' then device_hash_value when 'host' then coalesce(host_id_value::text,'none') else 'global' end;
    window_start:=to_timestamp(floor(extract(epoch from now())/rule.window_seconds)*rule.window_seconds);
    perform pg_advisory_xact_lock(hashtext(rule.id::text||dimension_value||window_start::text));
    insert into public.rate_limit_counters(rule_id,dimension_hash,window_started_at,weight,updated_at) values(rule.id,dimension_value,window_start,greatest(1,request_weight),now()) on conflict(rule_id,dimension_hash,window_started_at) do update set weight=public.rate_limit_counters.weight+greatest(1,request_weight),updated_at=now() returning * into counter;
    if counter.blocked_until is not null and counter.blocked_until>now() then allowed:=false;retry:=greatest(retry,ceil(extract(epoch from counter.blocked_until-now()))::integer);
    elsif counter.weight>rule.max_weight then update public.rate_limit_counters set blocked_until=now()+make_interval(secs=>rule.block_seconds) where rule_id=rule.id and dimension_hash=dimension_value and window_started_at=window_start;allowed:=false;retry:=greatest(retry,rule.block_seconds);end if;
    limits:=limits||jsonb_build_array(jsonb_build_object('dimension',rule.dimension_type,'weight',counter.weight,'limit',rule.max_weight,'window_seconds',rule.window_seconds));
  end loop;
  if not allowed then perform public.record_security_event_v1(actor_id_value,'rate_limit_block','warning','action',action_name_value,request_id_value,ip_hash_value,device_hash_value,null,jsonb_build_object('limits',limits));end if;
  return jsonb_build_object('allowed',allowed,'retry_after',retry,'limits',limits);
end$$;

create or replace function public.queue_media_scan_job_v1(target_asset uuid) returns bigint language plpgsql security definer set search_path=public as $$declare created bigint;begin if auth.role()<>'service_role' and not exists(select 1 from public.media_assets where id=target_asset and owner_id=auth.uid()) then raise exception 'not authorized';end if;insert into public.media_scan_jobs(media_asset_id) values(target_asset) on conflict(media_asset_id) where status in('pending','processing') do update set next_attempt_at=least(public.media_scan_jobs.next_attempt_at,now()) returning id into created;return created;end$$;
create or replace function public.claim_media_scan_jobs_v1(batch_size integer default 25) returns table(id bigint,media_asset_id uuid,bucket_id text,object_path text,mime_type text,original_name text,sha256 text) language plpgsql security definer set search_path=public as $$begin if auth.role()<>'service_role' then raise exception 'service role required';end if;return query with claimed as (select j.id from public.media_scan_jobs j where j.status in('pending','error') and j.next_attempt_at<=now() order by j.created_at limit greatest(1,least(batch_size,100)) for update skip locked) update public.media_scan_jobs j set status='processing',attempts=j.attempts+1,locked_at=now() from claimed c,public.media_assets a where j.id=c.id and a.id=j.media_asset_id returning j.id,j.media_asset_id,a.bucket_id,a.object_path,a.mime_type,a.original_name,a.sha256;end$$;
create or replace function public.complete_media_scan_job_v1(target_job bigint,scan_status_value text,scanner_value text,scan_details jsonb) returns boolean language plpgsql security definer set search_path=public as $$declare asset uuid;final_status text:=case when scan_status_value in('clean','infected','suspicious','error') then scan_status_value else 'error' end;begin if auth.role()<>'service_role' then raise exception 'service role required';end if;select media_asset_id into asset from public.media_scan_jobs where id=target_job for update;if asset is null then return false;end if;update public.media_scan_jobs set status=final_status,scanner=left(scanner_value,120),result=coalesce(scan_details,'{}'),completed_at=case when final_status<>'error' then now() end,next_attempt_at=case when final_status='error' then now()+make_interval(mins=>least(1440,greatest(5,attempts*attempts*5))) else next_attempt_at end where id=target_job;update public.media_assets set scan_status=final_status,scanner=left(scanner_value,120),malware_scan_provider=left(scanner_value,120),malware_scan_result=coalesce(scan_details,'{}'),scan_completed_at=now(),status=case when final_status='clean' and status='quarantined' then 'approved' when final_status in('infected','suspicious') then 'rejected' when final_status='error' and status='approved' then 'quarantined' else status end,approved_at=case when final_status='clean' then coalesce(approved_at,now()) else approved_at end where id=asset;update public.verification_documents set review_status=case when final_status='clean' then 'pending_review' when final_status in('infected','suspicious') then 'rejected' else review_status end where media_asset_id=asset and review_status='pending_scan';if final_status in('infected','suspicious') then perform public.record_security_event_v1((select owner_id from public.media_assets where id=asset),'malware_scan_detection','high','media_asset',asset::text,null,null,null,null,jsonb_build_object('status',final_status,'scanner',scanner_value));end if;return true;end$$;

create or replace function public.can_access_private_media_v1(target_asset uuid) returns jsonb language plpgsql stable security definer set search_path=public as $$declare asset public.media_assets%rowtype;privileged boolean:=false;allowed boolean:=false;begin select * into asset from public.media_assets where id=target_asset;if asset.id is null then return jsonb_build_object('allowed',false);end if;privileged:=public.has_privileged_role_v1(array['super_admin','trust_safety','content_moderator','verification','security']);allowed:=privileged or asset.owner_id=auth.uid() or (asset.target_type='conversation' and exists(select 1 from public.conversation_members cm where cm.conversation_id=asset.target_id and cm.profile_id=auth.uid() and cm.left_at is null)) or (asset.target_type='event' and public.can_manage_event(asset.target_id)) or (asset.target_type='location' and public.can_manage_location(asset.target_id));return jsonb_build_object('allowed',allowed,'privileged',privileged);end$$;

create or replace function public.admin_moderation_action_v1(target_case uuid,action_name text,action_payload jsonb,request_id_value text) returns jsonb language plpgsql security definer set search_path=public as $$
declare actor uuid:=auth.uid();item public.moderation_cases%rowtype;before_value jsonb;after_value jsonb;reason_value text:=left(coalesce(action_payload->>'reason',''),2000);priority_value text:=coalesce(action_payload->>'priority','normal');subject_uuid uuid;appeal_id uuid;
begin
  if not public.has_privileged_role_v1(array['super_admin','trust_safety','content_moderator','verification','support','finance_ops','security','incident_commander']) then raise exception 'not authorized';end if;
  select * into item from public.moderation_cases where id=target_case for update;if item.id is null then raise exception 'case unavailable';end if;before_value:=to_jsonb(item);begin subject_uuid:=item.subject_id::uuid;exception when invalid_text_representation then subject_uuid:=null;end;
  if action_name in('suspend_user','ban_user','restore_user','delist_event','cancel_event','relist_event','delist_location','relist_location','remove_message','remove_comment','restrict_conversation','reopen_conversation','suspend_host','restore_host') and not public.has_privileged_role_v1(array['super_admin','trust_safety','content_moderator']) then raise exception 'trust and safety role required';end if;
  if action_name in('approve_host_verification','reject_host_verification','approve_verification_document','reject_verification_document','approve_location_claim','reject_location_claim','quarantine_media','approve_media') and not public.has_privileged_role_v1(array['super_admin','trust_safety','verification']) then raise exception 'verification role required';end if;
  if action_name in('freeze_payouts','unfreeze_payouts','fraud_hold_order','release_fraud_hold','void_ticket','restore_ticket','approve_refund','decline_refund') and not public.has_privileged_role_v1(array['super_admin','finance_ops','incident_commander']) then raise exception 'finance role required';end if;
  if action_name in('uphold_appeal','overturn_appeal') and not public.has_privileged_role_v1(array['super_admin','trust_safety','support']) then raise exception 'appeals role required';end if;
  if char_length(reason_value)<8 and action_name not in('assign_self','preserve_evidence','set_priority') then raise exception 'a specific reason is required';end if;

  if action_name='assign_self' then update public.moderation_cases set assigned_to=actor,assigned_at=now(),state=case when state='open' then 'triaged' else state end where id=item.id;
  elsif action_name='set_priority' then if priority_value not in('low','normal','high','urgent','emergency') then raise exception 'invalid priority';end if;update public.moderation_cases set priority=priority_value where id=item.id;
  elsif action_name='preserve_evidence' then perform public.preserve_case_evidence_v1(item.id,item.subject_type,item.subject_id);
  elsif action_name in('resolve','dismiss') then update public.moderation_cases set state=case when action_name='resolve' then 'resolved' else 'dismissed' end,resolution_code=action_name,resolution_note=reason_value,resolved_at=now() where id=item.id;
  elsif action_name='escalate_emergency' then update public.moderation_cases set priority='emergency',emergency_escalated_at=now(),queue_key='emergency' where id=item.id;insert into public.security_alerts(title,severity,metadata) values('Emergency moderation escalation','critical',jsonb_build_object('case_id',item.id,'subject_type',item.subject_type,'subject_id',item.subject_id));
  elsif action_name='suspend_user' and item.subject_type='profile' then update public.profiles set suspended_at=coalesce(suspended_at,now()),moderation_state='suspended',ban_reason=reason_value where id=subject_uuid;
  elsif action_name='ban_user' and item.subject_type='profile' then update public.profiles set banned_at=coalesce(banned_at,now()),suspended_at=coalesce(suspended_at,now()),moderation_state='banned',ban_reason=reason_value where id=subject_uuid;
  elsif action_name='restore_user' and item.subject_type='profile' then update public.profiles set banned_at=null,suspended_at=null,moderation_state='active',ban_reason=null where id=subject_uuid;
  elsif action_name in('delist_event','cancel_event','relist_event') and item.subject_type='event' then perform set_config('puddle.allow_status_transition','on',true);update public.events set delisted_at=case when action_name='relist_event' then null else now() end,moderation_hold_at=case when action_name='relist_event' then null else now() end,moderation_reason=case when action_name='relist_event' then null else reason_value end,status=case when action_name='cancel_event' then 'cancelled'::public.event_status when action_name='relist_event' then 'published'::public.event_status else status end where id=subject_uuid;
  elsif action_name in('delist_location','relist_location') and item.subject_type='location' then perform set_config('puddle.allow_status_transition','on',true);update public.locations set delisted_at=case when action_name='relist_location' then null else now() end,moderation_hold_at=case when action_name='relist_location' then null else now() end,moderation_reason=case when action_name='relist_location' then null else reason_value end,status=case when action_name='relist_location' then 'published' else 'suspended' end where id=subject_uuid;
  elsif action_name in('suspend_host','restore_host') and item.subject_type='host' then update public.host_profiles set status=case when action_name='restore_host' then 'active' else 'suspended' end,moderation_state=case when action_name='restore_host' then 'active' else 'suspended' end,delisted_at=case when action_name='restore_host' then null else now() end where id=subject_uuid;
  elsif action_name in('freeze_payouts','unfreeze_payouts') and item.subject_type='host' then update public.host_profiles set payout_frozen_at=case when action_name='freeze_payouts' then now() else null end,payout_freeze_reason=case when action_name='freeze_payouts' then reason_value else null end where id=subject_uuid;
  elsif action_name in('restrict_conversation','reopen_conversation') and item.subject_type='conversation' then update public.conversations set moderation_state=case when action_name='reopen_conversation' then 'active' else 'restricted' end,moderated_at=now(),moderated_by=actor,moderation_reason=case when action_name='reopen_conversation' then null else reason_value end where id=subject_uuid;
  elsif action_name='remove_message' and item.subject_type='message' then update public.messages set state='moderator_removed',body='Message removed by moderation',moderator_removed_at=now(),moderator_removed_by=actor,moderator_reason=reason_value,metadata='{}' where id=item.subject_id::bigint;
  elsif action_name='remove_comment' and item.subject_type='comment' then update public.social_comments set deleted_at=coalesce(deleted_at,now()),body='Comment removed by moderation',moderator_removed_at=now(),moderator_removed_by=actor,moderator_reason=reason_value where id=item.subject_id::bigint;
  elsif action_name in('approve_host_verification','reject_host_verification') and item.subject_type='host' then update public.host_profiles set verification_status=case when action_name='approve_host_verification' then 'verified' else 'rejected' end,moderation_state=case when action_name='approve_host_verification' then 'active' else moderation_state end where id=subject_uuid;
  elsif action_name in('approve_verification_document','reject_verification_document') and item.subject_type='verification_document' then update public.verification_documents set review_status=case when action_name='approve_verification_document' then 'verified' else 'rejected' end,reviewed_by=actor,reviewed_at=now() where id=subject_uuid and review_status='pending_review';
  elsif action_name in('approve_location_claim','reject_location_claim') and item.subject_type='location_claim' then update public.location_claims set status=case when action_name='approve_location_claim' then 'approved' else 'rejected' end,reviewed_by=actor,reviewed_at=now(),review_note=reason_value where id=subject_uuid;if action_name='approve_location_claim' then update public.locations l set claimed_by_host_id=c.host_profile_id,claimed_at=now() from public.location_claims c where c.id=subject_uuid and l.id=c.location_id and c.host_profile_id is not null;end if;
  elsif action_name in('quarantine_media','approve_media') and item.subject_type='media' then if action_name='approve_media' and not exists(select 1 from public.media_assets where id=subject_uuid and scan_status='clean') then raise exception 'media scan is not clean';end if;update public.media_assets set status=case when action_name='quarantine_media' then 'quarantined' else 'approved' end,evidence_hold_at=case when action_name='quarantine_media' then now() else evidence_hold_at end where id=subject_uuid;
  elsif action_name in('fraud_hold_order','release_fraud_hold') and item.subject_type in('order','payment') then update public.orders set status=case when action_name='fraud_hold_order' then 'fraud_hold' else case when paid_at is not null then 'paid' else 'pending' end end,fraud_hold_reason=case when action_name='fraud_hold_order' then reason_value else null end where id=subject_uuid;
  elsif action_name in('void_ticket','restore_ticket') and item.subject_type='ticket' then update public.tickets set status=case when action_name='void_ticket' then 'void' else 'valid' end,token_version=token_version+1,signed_token=null,signed_at=null,void_reason=case when action_name='void_ticket' then reason_value else null end,updated_at=now() where id=subject_uuid and (action_name='void_ticket' or exists(select 1 from public.orders o where o.id=public.tickets.order_id and o.status='paid'));
  elsif action_name in('approve_refund','decline_refund') and item.subject_type='refund' then update public.refund_requests set status=case when action_name='approve_refund' then 'approved' else 'declined' end,decided_by=actor,decided_at=now(),decision_note=reason_value,updated_at=now() where id=subject_uuid and status='requested';
  elsif action_name in('uphold_appeal','overturn_appeal') then select id into appeal_id from public.moderation_appeals where case_id=item.id and state in('submitted','assigned','reviewing') order by created_at desc limit 1 for update;if appeal_id is null then raise exception 'open appeal unavailable';end if;update public.moderation_appeals set state=case when action_name='overturn_appeal' then 'overturned' else 'upheld' end,decision_reason=reason_value,decided_by=actor,decided_at=now() where id=appeal_id;update public.moderation_cases set state='resolved',resolution_code=action_name,resolution_note=reason_value,resolved_at=now() where id=item.id;
  else raise exception 'action is not valid for this case';end if;
  select to_jsonb(c) into after_value from public.moderation_cases c where c.id=item.id;insert into public.moderation_actions(case_id,actor_id,action,reason,before_data,after_data,request_id) values(item.id,actor,action_name,reason_value,before_value,after_value,left(request_id_value,120));perform public.write_security_audit_v1(actor,action_name,item.subject_type,item.subject_id,before_value,after_value,reason_value,request_id_value,null,null);return jsonb_build_object('ok',true,'case_id',item.id,'action',action_name);
end$$;
create or replace function public.admin_dashboard_v1() returns jsonb language plpgsql stable security definer set search_path=public as $$begin if not public.has_privileged_role_v1(array['super_admin','trust_safety','content_moderator','verification','support','finance_ops','security','incident_commander']) then raise exception 'not authorized';end if;return jsonb_build_object('counts',jsonb_build_object('open_cases',(select count(*) from public.moderation_cases where state not in('resolved','dismissed','closed')),'sla_breaches',(select count(*) from public.moderation_cases where state not in('resolved','dismissed','closed') and sla_due_at<now()),'open_alerts',(select count(*) from public.security_alerts where state in('open','acknowledged','investigating')),'pending_scans',(select count(*) from public.media_scan_jobs where status in('pending','processing','error')),'appeals',(select count(*) from public.moderation_appeals where state in('submitted','assigned','reviewing'))),'urgent',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select id,case_number,title,priority,sla_due_at from public.moderation_cases where state not in('resolved','dismissed','closed') and priority in('urgent','emergency') order by priority_rank,sla_due_at limit 10)x),'alerts',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select id,title,severity,state,created_at from public.security_alerts where state in('open','acknowledged','investigating') order by created_at desc limit 10)x));end$$;

create or replace function public.admin_content_review_queue_v1() returns jsonb language plpgsql stable security definer set search_path=public as $$begin if not public.has_privileged_role_v1(array['super_admin','trust_safety','content_moderator','verification']) then raise exception 'not authorized';end if;return jsonb_build_object('content',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select 'event' subject_type,id::text subject_id,title,coalesce(moderation_reason,status::text) reason from public.events where status in('pending_review','suspended') or moderation_hold_at is not null union all select 'location',id::text,name,coalesce(moderation_reason,status) from public.locations where status in('pending_review','suspended') or moderation_hold_at is not null limit 100)x),'verification',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select 'location_claim' subject_type,id::text subject_id,'Location claim' title,status state from public.location_claims where status in('pending','under_review') union all select 'host',id::text,name,verification_status from public.host_profiles where verification_status='pending' union all select 'verification_document',id::text,document_kind,review_status from public.verification_documents where review_status='pending_review' limit 100)x),'media',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select id,original_name,scan_status,status,created_at from public.media_assets where scan_status in('pending','suspicious','infected','error') order by created_at limit 100)x));end$$;

create or replace function public.admin_finance_queue_v1() returns jsonb language plpgsql stable security definer set search_path=public as $$begin if not public.has_privileged_role_v1(array['super_admin','finance_ops','incident_commander']) then raise exception 'not authorized';end if;return jsonb_build_object('counts',jsonb_build_object('refunds',(select count(*) from public.refund_requests where status in('requested','approved','processing')),'disputes',(select count(*) from public.stripe_disputes where status not in('won','lost','closed')),'failed_payouts',(select count(*) from public.stripe_payouts where status='failed'),'frozen_hosts',(select count(*) from public.host_profiles where payout_frozen_at is not null)),'exceptions',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select 'refund' kind,id::text,status,amount_cents,currency from public.refund_requests where status in('requested','approved','processing','failed') union all select 'dispute',id::text,status,amount_cents,currency from public.stripe_disputes where status not in('won','lost','closed') union all select 'payout',id::text,status,amount_cents,currency from public.stripe_payouts where status='failed' limit 100)x));end$$;

create or replace function public.admin_security_dashboard_v1() returns jsonb language plpgsql stable security definer set search_path=public as $$begin if not public.has_privileged_role_v1(array['super_admin','security','incident_commander']) then raise exception 'not authorized';end if;return jsonb_build_object('counts',jsonb_build_object('critical_alerts',(select count(*) from public.security_alerts where severity='critical' and state not in('resolved','dismissed')),'high_events_24h',(select count(*) from public.security_events where severity in('high','critical') and created_at>now()-interval '24 hours'),'rate_blocks_1h',(select count(*) from public.security_events where event_type='rate_limit_block' and created_at>now()-interval '1 hour'),'linked_signals',(select count(*) from public.linked_account_signals where reviewed_at is null)),'alerts',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select id,title,severity,state,created_at from public.security_alerts where state not in('resolved','dismissed') order by created_at desc limit 50)x),'rate_limits',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select r.action_name,r.dimension_type,sum(c.weight)::bigint count from public.rate_limit_counters c join public.rate_limit_rules r on r.id=c.rule_id where c.updated_at>now()-interval '1 hour' group by r.action_name,r.dimension_type order by count desc limit 30)x),'linked_accounts',(select coalesce(jsonb_agg(to_jsonb(x)),'[]') from(select id,profile_a,profile_b,signal_type,confidence,created_at from public.linked_account_signals where reviewed_at is null order by confidence desc limit 30)x));end$$;
