-- Complete user-facing controls that were present in the UI but not functional.
-- Adds first-class location reviews, outgoing friend-request cancellation, and
-- catalogue-wide map search while preserving explicit public/private boundaries.

create table if not exists public.location_reviews (
  id bigint generated by default as identity primary key,
  location_id uuid not null references public.locations(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  body text not null default '' check (char_length(body) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (location_id, author_id)
);

create index if not exists location_reviews_location_idx
  on public.location_reviews(location_id, created_at desc);
create index if not exists location_reviews_author_idx
  on public.location_reviews(author_id, updated_at desc);

alter table public.location_reviews enable row level security;

revoke all on table public.location_reviews from anon;
grant select on table public.location_reviews to authenticated;
revoke insert, update, delete on table public.location_reviews from authenticated;

-- Direct reads are limited to published, public, non-private-address locations.
drop policy if exists "location reviews visible for public places" on public.location_reviews;
create policy "location reviews visible for public places"
on public.location_reviews for select
to authenticated
using (
  exists (
    select 1
    from public.locations l
    where l.id = location_reviews.location_id
      and l.status = 'published'
      and l.visibility = 'public'
      and not coalesce(l.has_private_address, false)
  )
);

create or replace function public.location_reviews_v1(target_location uuid)
returns table(
  id bigint,
  author_id uuid,
  display_name text,
  username text,
  avatar_path text,
  rating smallint,
  body text,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;
  if not exists (
    select 1 from public.locations l
    where l.id=target_location
      and l.status='published'
      and l.visibility='public'
      and not coalesce(l.has_private_address,false)
  ) then raise exception 'Place unavailable.'; end if;

  return query
  select r.id,r.author_id,p.display_name,p.username,p.avatar_path,
         r.rating,r.body,r.created_at,r.updated_at
  from public.location_reviews r
  join public.profiles p on p.id=r.author_id and p.suspended_at is null
  where r.location_id=target_location
  order by r.updated_at desc,r.id desc
  limit 200;
end;
$$;

create or replace function public.upsert_location_review_v1(
  target_location uuid,
  review_rating integer,
  review_body text default ''
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare review_id bigint;
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;
  if review_rating is null or review_rating < 1 or review_rating > 5 then
    raise exception 'Rating must be between 1 and 5.';
  end if;
  if not exists (
    select 1 from public.locations l
    where l.id=target_location
      and l.status='published'
      and l.visibility='public'
      and not coalesce(l.has_private_address,false)
  ) then raise exception 'Place unavailable.'; end if;

  insert into public.location_reviews(location_id,author_id,rating,body,created_at,updated_at)
  values(target_location,auth.uid(),review_rating,left(trim(coalesce(review_body,'')),2000),now(),now())
  on conflict(location_id,author_id) do update
    set rating=excluded.rating,
        body=excluded.body,
        updated_at=now()
  returning id into review_id;

  return review_id;
end;
$$;

create or replace function public.delete_location_review_v1(target_location uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;
  delete from public.location_reviews
  where location_id=target_location and author_id=auth.uid();
  return found;
end;
$$;

create or replace function public.social_cancel_friend_request_v1(target uuid)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;
  if target is null or target=auth.uid() then raise exception 'Friend request is unavailable.'; end if;

  update public.friendships
  set state='removed'
  where requester_id=auth.uid()
    and addressee_id=target
    and state='pending';

  if not found then raise exception 'Friend request is unavailable.'; end if;
  return true;
end;
$$;

-- Catalogue-wide search for the map. This function deliberately exposes only
-- fields that are already safe for published, public, non-private locations.
create or replace function public.public_map_location_search_v1(
  search_term text,
  result_limit integer default 50
)
returns table(
  id uuid,
  slug text,
  name text,
  summary text,
  kind text,
  neighborhood text,
  city text,
  latitude double precision,
  longitude double precision,
  cover_path text
)
language plpgsql
stable
security definer
set search_path=public
as $$
declare term text;
begin
  if auth.uid() is null then raise exception 'Authentication required.'; end if;
  term := trim(regexp_replace(coalesce(search_term,''),'[%_]','','g'));
  if term = '' then return; end if;

  return query
  select l.id,l.slug,l.name,l.summary,l.kind::text,l.neighborhood,l.city,
         l.latitude::double precision,l.longitude::double precision,l.cover_path
  from public.locations l
  where l.status='published'
    and l.visibility='public'
    and not coalesce(l.has_private_address,false)
    and l.latitude is not null
    and l.longitude is not null
    and (
      l.name ilike '%'||term||'%'
      or coalesce(l.city,'') ilike '%'||term||'%'
      or coalesce(l.neighborhood,'') ilike '%'||term||'%'
      or coalesce(l.kind::text,'') ilike '%'||term||'%'
    )
  order by
    case when lower(l.name)=lower(term) then 0
         when lower(l.name) like lower(term)||'%' then 1
         else 2 end,
    l.name,
    l.city nulls last
  limit greatest(1,least(coalesce(result_limit,50),100));
end;
$$;

revoke all on function public.location_reviews_v1(uuid) from public,anon;
revoke all on function public.upsert_location_review_v1(uuid,integer,text) from public,anon;
revoke all on function public.delete_location_review_v1(uuid) from public,anon;
revoke all on function public.social_cancel_friend_request_v1(uuid) from public,anon;
revoke all on function public.public_map_location_search_v1(text,integer) from public,anon;

grant execute on function public.location_reviews_v1(uuid) to authenticated;
grant execute on function public.upsert_location_review_v1(uuid,integer,text) to authenticated;
grant execute on function public.delete_location_review_v1(uuid) to authenticated;
grant execute on function public.social_cancel_friend_request_v1(uuid) to authenticated;
grant execute on function public.public_map_location_search_v1(text,integer) to authenticated;
