import { NextResponse } from 'next/server'
import { requirePrivilegedApi } from '@/lib/auth/privileged'
import { verifyCsrf } from '@/lib/security/csrf'
import { enforceRateLimit } from '@/lib/security/rate-limit'
import { readJsonLimited, safeSecurityError } from '@/lib/security/request'
import { object, string } from '@/lib/security/schema'
import { recordSecurityEvent } from '@/lib/security/audit'

export const runtime='nodejs';export const dynamic='force-dynamic'
const SUBJECTS=['event','location','host','profile','conversation','message','comment','plan','location_claim','verification_document','media','ticket','order','payment','dispute','payout']
export async function POST(request){let session;try{if(!verifyCsrf(request))return NextResponse.json({error:'Security token is invalid.'},{status:403});session=await requirePrivilegedApi();const limited=await enforceRateLimit({headers:request.headers,userId:session.user.id,action:'admin_case_action'});if(!limited.allowed)return NextResponse.json({error:'Too many case actions.'},{status:429});const body=object(await readJsonLimited(request,20_000));const subjectType=string(body.subjectType,{name:'subject type',choices:SUBJECTS,max:40});const subjectId=string(body.subjectId,{name:'subject ID',min:1,max:200});const title=string(body.title,{name:'title',min:3,max:240});const summary=string(body.summary,{name:'summary',min:8,max:4000});const category=string(body.category,{name:'category',min:2,max:80});const priority=string(body.priority,{name:'priority',choices:['low','normal','high','urgent','emergency'],max:20});const queue=string(body.queue,{name:'queue',choices:['general','content','safety','verification','payments','appeals','security','emergency'],max:30});const{data,error}=await session.supabase.rpc('open_moderation_case_v1',{subject_type_value:subjectType,subject_id_value:subjectId,case_title:title,case_summary:summary,case_category:category,case_priority:priority,queue_value:queue,request_id_value:limited.requestId});if(error)throw error;await recordSecurityEvent({headers:request.headers,actorId:session.user.id,eventType:'moderation_case_opened',severity:priority==='emergency'?'critical':priority==='urgent'?'high':'notice',targetType:subjectType,targetId:subjectId,metadata:{case_id:data,queue}});return NextResponse.json({ok:true,caseId:data})}catch(error){return NextResponse.json({error:safeSecurityError(error,'The moderation case could not be opened.')},{status:error?.status||400})}}
